use_frameworks!

platform :ios, '10.0'

target 'mParticle-Example_Example' do
  pod 'mParticle-Example', :path => '../'

  target 'mParticle-Example_Tests' do
    inherit! :search_paths

    
  end
end
